---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: default
spec:
  containers:
  - name: httpbin
    image: docker.io/kennethreitz/httpbin
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
